# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NfnCli < Formula
  desc "CLI for the Nordic Financial News API"
  homepage "https://github.com/nordic-financial-news/nfn-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_darwin_amd64.tar.gz"
      sha256 "4397f76bd1d795816d193ad2969e9bc90d6a287be95af15c4c3bcf8f72ce2fe2"

      define_method(:install) do
        bin.install "nfn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_darwin_arm64.tar.gz"
      sha256 "58801dabe59799ab11437e1e926a84366c579530cec59af69a9c71111c20aaca"

      define_method(:install) do
        bin.install "nfn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_linux_amd64.tar.gz"
      sha256 "3b3ccf49ea8be9c4b934561459f84c75d54a7e3770a4604c30dcf020b9bc58e9"
      define_method(:install) do
        bin.install "nfn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_linux_arm64.tar.gz"
      sha256 "900a8dfe35393446e16b5a725dcc38ad8c8b8ef2b9684dcf77b1ba96083d02af"
      define_method(:install) do
        bin.install "nfn"
      end
    end
  end
end
