# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NfnCli < Formula
  desc "CLI for the Nordic Financial News API"
  homepage "https://github.com/nordic-financial-news/nfn-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_darwin_amd64.tar.gz"
      sha256 "ccaede15d9d313497b9c4131ffd6b65681d3529084d414a542669a79e482cae4"

      define_method(:install) do
        bin.install "nfn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_darwin_arm64.tar.gz"
      sha256 "fc472975e300fadfd59e65af7e66189a4b9cace994cd3b7792b0e0f7d827acb3"

      define_method(:install) do
        bin.install "nfn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_linux_amd64.tar.gz"
      sha256 "a6b2817f454370b675b41f57fcdb57e410a70653e6a828aa4098b6e3546058b8"
      define_method(:install) do
        bin.install "nfn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_linux_arm64.tar.gz"
      sha256 "37bf89f0cabd791ec5a1df7d72dba7e5bd4784d6a60c2fa721ce49e6be8d09ac"
      define_method(:install) do
        bin.install "nfn"
      end
    end
  end
end
