# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nfn < Formula
  desc "CLI for the Nordic Financial News API"
  homepage "https://github.com/nordic-financial-news/nfn-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_darwin_amd64.tar.gz"
      sha256 "f499035ce9e2eaf23646a3c1c907a68176de76e50ae8788916c5f6d7291765ce"

      define_method(:install) do
        bin.install "nfn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_darwin_arm64.tar.gz"
      sha256 "58711a65fa51b302cfc53ddf62cd7aa6ea2943abb471ef6f88ec2efe19c7bf39"

      define_method(:install) do
        bin.install "nfn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_linux_amd64.tar.gz"
      sha256 "7f45f22982f1538da07adbeb398435447dbea0f16b6434b590a18887b8a601ba"
      define_method(:install) do
        bin.install "nfn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_linux_arm64.tar.gz"
      sha256 "5335f4bd3c9c8d776f5d9e1a786c09b9af1487ef8536af6dcd3096e643aa50d1"
      define_method(:install) do
        bin.install "nfn"
      end
    end
  end
end
