# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nfn < Formula
  desc "CLI for the Nordic Financial News API"
  homepage "https://github.com/nordic-financial-news/nfn-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_darwin_amd64.tar.gz"
      sha256 "621db57a4e0f72400ea4a979caad623b41daae092b2ff0a5487673ab2be651a8"

      define_method(:install) do
        bin.install "nfn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_darwin_arm64.tar.gz"
      sha256 "46f6100e6e12082353b772d46f4d30394d23808ec41ff38e322c026f302a30bf"

      define_method(:install) do
        bin.install "nfn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_linux_amd64.tar.gz"
      sha256 "f7f18f6e8371aa8d67c92f3c981f4db15ebfc19a43cb9a78782690cc68f22650"
      define_method(:install) do
        bin.install "nfn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nordic-financial-news/nfn-cli/releases/download/v0.1.0/nfn-cli_linux_arm64.tar.gz"
      sha256 "5ae31e09180b87288c537643b6d17598584b718b2ba8b78998b9863633e00bbd"
      define_method(:install) do
        bin.install "nfn"
      end
    end
  end
end
